### ISSUE TITLE
docker image - su: must be run from a terminal

### ISSUE THREAD

**Issue by geoberle** [rchakode/realopinsight#16]
Thanks for RealOpInsight. What a great tool!

I tried to run the official Docker image rchakode/realopinsight:2019.r1.0 on a kubernetes cluster with tightened security. When starting the container, i get the following errormessage

runtime user is realopinsight
starting realopinsight-reportd service
su: must be run from a terminal

In such an environment all containers are started with a arbitrary/random user id and not the one specified in the Dockerfile. I can only assume, that it has something to do with that.

Since i did not find the Dockerfile used to build that image, i can't continue my investigation.

**Comment by rchakode** [comment]
Hi @geoberle,
And thanks to report this. 
You can find the Dockerfile in the distribution tarball. 

Regards, 
Rodrigue

**Comment by rchakode** [comment]
By the way @geoberle, if you improve the Dockerfile, can you please contribute back? It will help other people I think. Even a K8s deployment file can also help.

**Comment by geoberle** [comment]
Sure, I will!

**Comment by rchakode** [comment]
Hi @geoberle,
I don't know if you manage to build your own Docker image, but note that this issue is now fixed in version 2019.r1.1 just released.

Thanks again to have reported the issue.
