### ISSUE TITLE
error message at the end of the creation of the service

### ISSUE THREAD

**Issue by fredjol** [rchakode/realopinsight#17]
hello , i have an error message at the end of the creation of the service :
unexpected number of nodes for dynamic view file : 4
- base image : virtual box 2019r1 ( on vmware )
- hardware : 8 cores - 16 gb 
- monitoring : centreon / livestatus  ( 9k services ) and ( 1k hosts )

**Comment by rchakode** [comment]
Hi,
Can you please provide details on your setup and what you did?
* Version of RealOpInsight.
* Backend monitoring system. 
* how do you build the view in question.
Regards,

**Comment by fredjol** [comment]
hello, 
- our realopinsight version is 2019.R1.0.
- backend monitoring system is centreon engine fork nagios
- screenshots
![Capture 1](https://user-images.githubusercontent.com/50450413/57516408-f6488a00-7314-11e9-9d74-ddb94032a9b7.PNG)
![Capture 2](https://user-images.githubusercontent.com/50450413/57516424-fea0c500-7314-11e9-8e51-fe7460638aa0.PNG)
![Capture 3](https://user-images.githubusercontent.com/50450413/57516428-006a8880-7315-11e9-9f11-5f4d8433d5b4.PNG)

regards,

**Comment by rchakode** [comment]
Look weird, can you send us a copy of file mentioned in the error message?
Either attach here or send it by email at support @ realopinsight.com

**Comment by fredjol** [comment]
hi! I realized new tests following your answer. now I still have the error message when creating the service (see screenshot attached).  Can you tell me how to find , the copy of the file mentioned in the error message ?
  
![Capture 0](https://user-images.githubusercontent.com/50450413/57610545-4de33180-7571-11e9-8a73-3ee8d1aa4446.PNG)

**Comment by rchakode** [comment]
Hi,
Copying the file depend on how you setup RealOpInsight:
 * if you use the virtual machine distribution, use scp to copy the file. The default credentials are `ubuntu`/`ubuntu`.
* if you use a Docker instance, use `docker cp` command to copy the file from the container.

**Comment by fredjol** [comment]
hi, the problem was identified it was a saturation of the disk in terms of volume. We have created a new disk, this message does not appear since, so problem solved. We still have other problems and error messages, I'll come back to you if we do not find the solution. thank you .

**Comment by rchakode** [comment]
nice to hear that the problem is fixed.
