### ISSUE TITLE
remove services

### ISSUE THREAD

**Issue by fredjol** [rchakode/realopinsight#18]
hello , how to remove edited services in input selector ?

**Comment by fredjol** [comment]
> 
> hello ,
> how to remove edited services in input selector ?

**Comment by rchakode** [comment]
Hi,
What do you mean by input selector? Which version of RealOpInsight do you use? 
Do you have a screenshot to share.

**Comment by fredjol** [comment]
hello, 
- our realopinsight version is 2019.R1.0.
- backend monitoring system is centreon engine fork nagios 
- screenshots

![Capture 2](https://user-images.githubusercontent.com/50450413/57516277-b681a280-7314-11e9-8abd-f233c5620f96.PNG)

**Comment by rchakode** [comment]
I see,
Views deletion is available though the menu `Manage Operations Views`.

**Comment by fredjol** [comment]
ok thanks
