### ISSUE TITLE
error message : unexpected number of nodes for dynamic view files

### ISSUE THREAD

**Issue by fredjol** [rchakode/realopinsight#19]
Hi, when creating a service, I want to edit the message "Unexpected number of nodes for dynamic view files" appears.
![Capture nodes](https://user-images.githubusercontent.com/50450413/57680225-6c0e6780-762d-11e9-9bd7-dc4f2fb80f06.PNG)

**Comment by rchakode** [comment]
Hi @fredjol,

I can confirm that there is a regression there, we'll fix it in the next version.
Meanwhile you may consider to install an older version to work around this issue: https://github.com/rchakode/realopinsight/releases.

Thanks for reporting the issue. 

R.

**Comment by fredjol** [comment]
hi, thanks for your answer, we will continue later. Regards .

**Comment by rchakode** [comment]
Hi @fredjol,
This issue is now fixed in version 2019.r1.1 just released.

:)
