### ISSUE TITLE
Illegal instruction when install-distrib.sh

### ISSUE THREAD

**Issue by anshibanov** [rchakode/realopinsight#20]
Hi! 
Ubuntu 18.04 with last updates. When i start install i got error

`
DEBUG: Installing RealOpInsight 2019.r1.1...

DEBUG: stopping services... 

Failed to stop realopinsight-server.service: Unit realopinsight-server.service not loaded.

Failed to stop realopinsight-reportd.service: Unit realopinsight-reportd.service not loaded.

DEBUG: checking prerequisites...

DEBUG: Checking Graphviz => /usr/bin/dot... 

DEBUG: Creating destination fs tree...

DEBUG: Cleanup installation target directories...

DEBUG: Copying core distribution files...

DEBUG: Installing realopinsight-server.service script...

Created symlink /etc/systemd/system/multi-user.target.wants/realopinsight-server.service → 
/lib/systemd/system/realopinsight-server.service.

DEBUG: Initializing the database...

./install-distrib.sh: line 290: 14672 Illegal instruction     (core dumped)
 
LD_LIBRARY_PATH=${REALOPINSIGHT_INSTALL_PREFIX}/lib ${REALOPINSIGHT_INSTALL_PREFIX}/sbin/realopinsight-setupdb
`

**Comment by rchakode** [comment]
Hi @anshibanov,
Thank you to report this. 
This is normal, as binary package is currently provided for Ubuntu `16.04` LTS. 
We do not yet provide packages for Ubuntu 18.04.

**Comment by anshibanov** [comment]
Oh, thx< i try install on Ubuntu 16.04

**Comment by anshibanov** [comment]
I try ubuntu 16.04 and have same error:

```
DEBUG: Installing RealOpInsight 2019.r1.1...
DEBUG: stopping services... 
Failed to stop realopinsight-server.service: Unit realopinsight-server.service not loaded.
Failed to stop realopinsight-reportd.service: Unit realopinsight-reportd.service not loaded.
DEBUG: checking prerequisites...
DEBUG: Checking Graphviz => /usr/bin/dot... 
DEBUG: Creating destination fs tree...
DEBUG: Cleanup installation target directories...
DEBUG: Copying core distribution files...
DEBUG: Installing realopinsight-server.service script...
Created symlink from /etc/systemd/system/multi-user.target.wants/realopinsight-server.service to /lib/systemd/system/realopinsight-server.service.
DEBUG: Initializing the database...
./install-distrib.sh: line 290:  2657 Segmentation fault      LD_LIBRARY_PATH=${REALOPINSIGHT_INSTALL_PREFIX}/lib ${REALOPINSIGHT_INSTALL_PREFIX}/sbin/realopinsight-setupdb
orange@ubuntu:~/realopinsight-2019.r1.1.ubuntu1604.x86_64$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

```

**Comment by anshibanov** [comment]
@rchakode

**Comment by rchakode** [comment]
Hi @anshibanov,
Wow, looks weird indeed. 
Can you please give me the link on the version of Ubuntu ISO you installed. I'll try to reproduce on my side.

**Comment by anshibanov** [comment]
Sure
http://releases.ubuntu.com/16.04/ubuntu-16.04.6-server-amd64.iso

**Comment by rchakode** [comment]
In the meantime, can you try to install `sqlite3` from apt and retry the RealOpInsight installation please ?

**Comment by younitydev** [comment]
hi
i had the same issue with Ubuntu 16.04.6 LTS.
ive install sqlite3 but still, the installation fails 
appreciate your help
DEBUG: Installing RealOpInsight 2019.r1.1...
DEBUG: stopping services...
Failed to stop realopinsight-reportd.service: Unit realopinsight-reportd.service not loaded.
DEBUG: checking prerequisites...
DEBUG: Checking Graphviz => /usr/bin/dot...
DEBUG: Creating destination fs tree...
DEBUG: Cleanup installation target directories...
DEBUG: Copying core distribution files...
DEBUG: Initializing the database...
./install-distrib.sh: line 290:  8214 Segmentation fault      (core dumped) LD_LIBRARY_PATH=${REALOPINSIGHT_INSTALL_PREFIX}/lib ${REALOPINSIGHT_INSTALL_PREFIX}/sbin/realopinsight-setupdb

**Comment by rchakode** [comment]
Hi @younitydev,
Thank you for the report, we're instigating.
Can you confirm that you're using Ubuntu server (not desktop)?

**Comment by younitydev** [comment]
hi
yes ubuntu server fresh installed in aws

**Comment by younitydev** [comment]
what did you mean by installing dev files from apt?

**Comment by younitydev** [comment]
i tryed installing ver r1.0 but same issue

**Comment by younitydev** [comment]
any thoughts?

**Comment by rchakode** [comment]
can you try to install  `libsqlite3-dev` and re-run the installation?

**Comment by younitydev** [comment]
hi
it didnt help


Type a response: n
DEBUG: Installing RealOpInsight 2019.r1.1...
DEBUG: stopping services...
Failed to stop realopinsight-reportd.service: Unit realopinsight-reportd.service not loaded.
DEBUG: checking prerequisites...
DEBUG: Checking Graphviz => /usr/bin/dot...
DEBUG: Creating destination fs tree...
DEBUG: Cleanup installation target directories...
DEBUG: Copying core distribution files...
DEBUG: Initializing the database...
./install-distrib.sh: line 290:  8802 Segmentation fault      (core dumped) LD_LIBRARY_PATH=${REALOPINSIGHT_INSTALL_PREFIX}/lib ${REALOPINSIGHT_INSTALL_PREFIX}/sbin/realopinsight-setupdb
root@ip-172-31-44-170:~/realopinsight-2019.r1.1.ubuntu1604.x86_64# apt list --installed | grep libsqlite3-dev

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libsqlite3-dev/xenial-updates,xenial-security,now 3.11.0-1ubuntu1.2 amd64 [installed]
root@ip-172-31-44-170:~/realopinsight-2019.r1.1.ubuntu1604.x86_64#

**Comment by rchakode** [comment]
we'll continue our investigate.
In the meantime you may consider either the Docker distribution or the virtual machine for your use.

**Comment by younitydev** [comment]
could i install your vm in aws?

**Comment by rchakode** [comment]
normally yes, there is no restriction on where you want to install it.
you can either install the VM or deploy a container inside your VM on AWS

**Comment by lucky277** [comment]
Hi rrchakode 
Anyluck on this issue?

**Comment by rchakode** [comment]
Hi @lucky277 ,$
Unfortunately we didn't have time to work on this issue. 
Did you try the Docker image as suggested above ? It should provide you the same benefit than the binary distribution.

Regards,

**Comment by rchakode** [comment]
This issue is deprecated with the release v20.10.1, full containized. See the README for more details.
